### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ipedrazas** [agonzalezro/polo#36]
It's very hard to start using Polo. 

It would be nice to have a step by step tutorial to create your github pages using polo. Unfortunately, it is very hard to know how to set it up.

**Comment by agonzalezro** [comment]
Does this help? http://agonzalezro.github.io/how-to-automagically-generate-your-polo-blog-with-circleci.html

I don't actually understand what you are asking for, help about generating the blog with `polo` or help about uploading the htmls to `gh-page`s?

**Comment by agonzalezro** [comment]
@ipedrazas did the tutorial help?

**Comment by ipedrazas** [comment]
:+1:

**Comment by agonzalezro** [comment]
If you think that some extra info can be added. Please, let me know which one.
