### ISSUE TITLE
Template has Alex data

### ISSUE THREAD

**Issue by ipedrazas** [agonzalezro/polo#38]
when I create new page, the default template contains Alex twitter... doh!

**Comment by agonzalezro** [comment]
@ipedrazas the default template is linking to my twitter handle in the footer.

<img width="317" alt="screenshot 2015-11-02 21 07 50" src="https://cloud.githubusercontent.com/assets/205176/10892819/ce68d1d4-81a5-11e5-849a-f7fe345e15d3.png">

I think that this default "credits" are ok and easy to remove.

**Comment by agonzalezro** [comment]
@ipedrazas can I close this? Or would you add more info?
